using Microsoft.Maui.Storage;

namespace Nooria.Services;

public static class LocalizationService
{
    private static string _currentLanguage = "en";

    private static readonly Dictionary<string, Dictionary<string, string>> _translations = new()
    {
        ["en"] = new()
        {
            // Tabs
            ["Tab_Home"]              = "HOME",
            ["Tab_Monthly"]           = "MONTHLY",
            ["Tab_Qibla"]             = "QIBLA",
            ["Tab_Quran"]             = "QURAN",
            ["Tab_Settings"]          = "SETTINGS",

            // Main Page
            ["Greeting"]              = "Assalamu Alaikum",
            ["FastDay"]               = "Fast Day",
            ["UpcomingPrayer"]        = "UPCOMING PRAYER",
            ["Time"]                  = "TIME",
            ["StartsIn"]              = "STARTS IN",
            ["Hrs"]                   = "HOURS",
            ["Min"]                   = "MINUTE",
            ["Sec"]                   = "SECOND",
            ["Local"]                 = "LOCAL",
            //["CurrentPrayer"]         = "CURRENT PRAYER",
            ["NextIn"]                = "PRAYER TIME ENDS IN",
            ["DailyTimes"]            = "Daily Times",
            ["MonthlyTable"]          = "Monthly Table",

            // Prayer names
            ["Prayer_Fajr"]           = "Fajr",
            ["Prayer_Sunrise"]        = "Sunrise",
            ["Prayer_Dhuhr"]          = "Dhuhr",
            ["Prayer_Asr"]            = "Asr",
            ["Prayer_Maghrib"]        = "Maghrib",
            ["Prayer_Isha"]           = "Isha",

            // Monthly Page
            ["MonthlySchedule"]       = "Monthly Praying Times",
            ["Date"]                  = "Day",
            ["BenefitOfMonth"]        = "BENEFIT OF THE MONTH",
            ["BenefitQuote"]          = "\u201cTake advantage of five before five: your youth before your old age, your health before your sickness...\u201d",
            ["BenefitAttribution"]    = "\u2014 Hadith, Al-Hakim",

            // Qibla / Quran
            ["Qibla"]                 = "Qibla",
            ["Quran"]                 = "Quran",
            ["ComingSoon"]            = "Coming soon",

            // Settings
            ["Settings"]              = "Settings",
            ["AppLanguage"]           = "App Language",
            ["SelectLanguage"]        = "Select your language",
            ["Change"]                = "CHANGE",
            ["LocationThreshold"]     = "Location Update Threshold",
            ["LocationThresholdDesc"] = "Re-fetch prayer times when city changes after moving this distance",
            ["NotificationsAndPrefs"] = "NOTIFICATIONS & PREFERENCES",
            ["PrayerNotifications"]   = "Prayer Notifications",
            ["DarkMode"]              = "Dark Mode",
            ["LocationServices"]      = "Location Services",
            ["CalculationMethod"]     = "CALCULATION METHOD",
            ["FajrIshaMethod"]        = "Calculation Method",
            ["MuslimWorldLeague"]     = "Presidency of Religious Affairs (Türkiye)",
            ["Account"]               = "ACCOUNT",
            ["ProfileInformation"]    = "Profile Information",
            ["UpdatePersonalDetails"] = "Update your personal details",

            // City Search
            ["SelectCity"]            = "Select City",
            ["SearchCityHint"]        = "Type a city name…",
            ["UseCurrentLocation"]    = "Use Current Location",
            ["NoResults"]             = "No results found",

            // No Location Page
            ["NoLocationTitle"]       = "No Location Set",
            ["NoLocationDesc"]        = "To continue, grant location permission — or select your city below.",
            ["Or"]                    = "or",
            ["OpenSettings"]          = "Open Settings",
            ["LocationPermission"]    = "Location Permission",
            ["LocationPermDenied"]    = "Location access was denied. Please enable it in your device Settings.",

            // Calculation method
            ["CalcMethod"]            = "Calculation Method",
            ["CalcMethodDiyanet"]     = "Diyanet",
            ["CalcMethodQMI"]         = "Caucasus Muslims' Board",

            // Qibla
            ["QiblaInstruction"]      = "Place your device on a flat surface then move it",

            // Notifications
            ["Notif_Title"]           = "Prayer Time",
            ["Notif_BeforeBody"]      = "{0} in {1} min",
            ["Notif_BeforeBody_H"]    = "{0} in {1}h {2}min",
            ["Notif_OnBody"]          = "{0} prayer started",
            ["Notif_EndsBody"]        = "{0} ends in {1} min",
            ["Notif_EndsBody_H"]      = "{0} ends in {1}h {2}min",
            ["AppliesToAll"]          = "Applies to all prayer times",
            ["CustomizePerPrayer"]    = "Customize per prayer",

            // Settings page UI
            ["Sett_Before"]          = "Before Prayer Time",
            ["Sett_On"]              = "On Prayer Time",
            ["Sett_Ends"]            = "Prayer Time Ends In",
            ["Sett_SoundAdhan"]      = "Sound",
            ["Sett_PlayNow"]         = "Play Sound Now",
            ["Sett_PlayNowDesc"]     = "Plays audio directly — no notification needed",
            ["Sett_TestNotif"]       = "Test Notification",
            ["Sett_TestNotifDesc"]   = "Fires in 10 s — go to home screen, keep app alive",
            ["Sett_ViewLog"]         = "Notification Log",
            ["Sett_ViewLogDesc"]     = "Tap to view debug log",
            ["Sett_SelectSound"]     = "Select Sound",
            ["Sett_PlayWhich"]       = "Play which sound?",
            ["Sett_TestWhich"]       = "Test with which sound?",
            ["Sett_TestAlarmTitle"]  = "Test Alarm Scheduled",
            ["Sett_TestAlarmBody"]   = "Sound: {0}\nFires in 10 seconds.\n\n1. Tap OK\n2. Swipe up to go home\n3. Wait for the notification",
            ["Sett_LogTitle"]        = "Notification Log (Copied!)",
            ["Sett_LogClearedTitle"] = "Log Cleared",
            ["Sett_LogClearedBody"]  = "Log file has been cleared.",
            ["Cancel"]               = "Cancel",
            ["OK"]                   = "OK",

            // Calculation method names
            ["CalcMethod_0"]         = "Shia Ithna-Ansari",
            ["CalcMethod_1"]         = "University of Islamic Sciences, Karachi",
            ["CalcMethod_2"]         = "Islamic Society of North America (ISNA)",
            ["CalcMethod_3"]         = "Muslim World League (MWL)",
            ["CalcMethod_4"]         = "Umm Al-Qura University, Makkah",
            ["CalcMethod_5"]         = "Egyptian General Authority of Survey",
            ["CalcMethod_7"]         = "Institute of Geophysics, University of Tehran",
            ["CalcMethod_8"]         = "Gulf Region",
            ["CalcMethod_9"]         = "Kuwait",
            ["CalcMethod_10"]        = "Qatar",
            ["CalcMethod_11"]        = "Majlis Ugama Islam Singapura (MUIS)",
            ["CalcMethod_12"]        = "Union Organization Islamic de France",
            ["CalcMethod_13"]        = "Diyanet \u0130\u015fleri Ba\u015fkanl\u0131\u011f\u0131, Turkey",
            ["CalcMethod_14"]        = "Spiritual Administration of Muslims of Russia",
            ["CalcMethod_15"]        = "Moonsighting Committee Worldwide (Khalid Shaukat)",
            ["CalcMethod_16"]        = "Dubai",
            ["CalcMethod_17"]        = "Jabatan Kemajuan Islam Malaysia (JAKIM)",
            ["CalcMethod_18"]        = "Jordan",
            ["CalcMethod_19"]        = "Islamic University of Madinah",
            ["CalcMethod_20"]        = "Kementerian Agama Republik Indonesia",
            ["CalcMethod_21"]        = "Morocco",
            ["CalcMethod_22"]        = "Comunidade Islamica de Lisboa",
            ["CalcMethod_23"]        = "Ministry of Awqaf and Islamic Affairs, Algeria",
            ["CalcMethod_24"]        = "Caucasus Muslims Board (QMI)",
            ["CalcMethod_99"]        = "Custom",

            // Calc config page
            ["CalcConfig_Title"]      = "Calculation Parameters",
            ["CalcConfig_Shafaq"]     = "Shafaq (Twilight)",
            ["CalcConfig_ShafaqDesc"] = "Type of twilight used for Isha calculation",
            ["CalcConfig_Tune"]       = "Tune (Offsets)",
            ["CalcConfig_TuneDesc"]   = "Comma-separated offsets in minutes for each prayer",
            ["CalcConfig_School"]     = "Juristic School (Asr)",
            ["CalcConfig_Midnight"]   = "Midnight Mode",
            ["CalcConfig_LatAdj"]     = "Latitude Adjustment",
            ["CalcConfig_Calendar"]   = "Calendar Method",
            ["CalcConfig_Apply"]      = "Apply",
            ["CalcConfig_Reset"]      = "Reset to Defaults",
            ["Shafaq_General"]        = "General",
            ["Shafaq_Ahmer"]          = "Ahmer (Red)",
            ["Shafaq_Abyad"]          = "Abyad (White)",
            ["School_Shafi"]          = "Shafi / Standard",
            ["School_Hanafi"]         = "Hanafi",
            ["Midnight_Standard"]     = "Standard (Mid Sunset to Sunrise)",
            ["Midnight_Jafari"]       = "Jafari (Mid Sunset to Fajr)",
            ["LatAdj_None"]           = "No Adjustment",
            ["LatAdj_Middle"]         = "Middle of the Night",
            ["LatAdj_Seventh"]        = "One-Seventh of the Night",
            ["LatAdj_Angle"]          = "Angle-Based",
            ["Calendar_HJCoSA"]       = "Hijri (HJCoSA)",
            ["Calendar_UAQ"]          = "Umm al-Qura (UAQ)",
            ["Calendar_DIYANET"]      = "Diyanet",
            ["Calendar_MATHEMATICAL"] = "Mathematical",
        },

        ["tr"] = new()
        {
            // Tabs
            ["Tab_Home"]              = "ANA SAYFA",
            ["Tab_Monthly"]           = "VAKİTLER",
            ["Tab_Qibla"]             = "K\u0130BLE",
            ["Tab_Quran"]             = "KURAN",
            ["Tab_Settings"]          = "AYARLAR",

            // Main Page
            ["Greeting"]              = "Esselamu Aleykum",
            ["FastDay"]               = "Oru\u00e7 G\u00fcn\u00fc",
            ["UpcomingPrayer"]        = "YAKLA\u015eAN NAMAZ",
            ["Time"]                  = "VAK\u0130T",
            ["StartsIn"]              = "BA\u015eLANGICI",
            ["Hrs"]                   = "SAAT",
            ["Min"]                   = "DAKİKA",
            ["Sec"]                   = "SANİYE",
            ["Local"]                 = "YEREL",
            //["CurrentPrayer"]         = "MEVCUT NAMAZ",
            ["NextIn"]                = "VAKTİN ÇIKMASINA",
            ["DailyTimes"]            = "G\u00fcnl\u00fck Vakitler",
            ["MonthlyTable"]          = "Ayl\u0131k Tablo",

            // Prayer names
            ["Prayer_Fajr"]           = "Sabah",
            ["Prayer_Sunrise"]        = "G\u00fcne\u015f",
            ["Prayer_Dhuhr"]          = "\u00d6\u011fle",
            ["Prayer_Asr"]            = "\u0130kindi",
            ["Prayer_Maghrib"]        = "Ak\u015fam",
            ["Prayer_Isha"]           = "Yats\u0131",

            // Monthly Page
            ["MonthlySchedule"]       = "Ayl\u0131k Namaz Vakitleri",
            ["Date"]                  = "Gün",
            ["BenefitOfMonth"]        = "AYIN FAYDALARI",
            ["BenefitQuote"]          = "\u201cBe\u015ften \u00f6nce be\u015ften yararlan: ya\u015fl\u0131l\u0131\u011f\u0131ndan \u00f6nce gen\u00e7li\u011fin, hastal\u0131\u011f\u0131ndan \u00f6nce sa\u011fl\u0131\u011f\u0131n...\u201d",
            ["BenefitAttribution"]    = "\u2014 Hadis, El-Hakim",

            // Qibla / Quran
            ["Qibla"]                 = "K\u0131ble",
            ["Quran"]                 = "Kuran",
            ["ComingSoon"]            = "\u00c7ok yak\u0131nda",

            // Settings
            ["Settings"]              = "Ayarlar",
            ["AppLanguage"]           = "Uygulama Dili",
            ["SelectLanguage"]        = "Dil seçin",
            ["Change"]                = "DE\u011e\u0130\u015eT\u0130R",
            ["LocationThreshold"]     = "Konum G\u00fcncelleme E\u015fi\u011fi",
            ["LocationThresholdDesc"] = "Bu mesafeyi a\u015f\u0131p \u015fehir de\u011fi\u015firse namaz vakitleri yenilenir",
            ["NotificationsAndPrefs"] = "B\u0130LD\u0130R\u0130MLER VE TERC\u0130HLER",
            ["PrayerNotifications"]   = "Namaz Bildirimleri",
            ["DarkMode"]              = "Karanl\u0131k Mod",
            ["LocationServices"]      = "Konum Hizmetleri",
            ["CalculationMethod"]     = "HESAPLAMA Y\u00d6NTEM\u0130",
            ["FajrIshaMethod"]        = "Hesablama Y\u00f6ntemi",
            ["MuslimWorldLeague"]     = "Diyanet İşleri Başkanlığı",
            ["Account"]               = "HESAP",
            ["ProfileInformation"]    = "Profil Bilgileri",
            ["UpdatePersonalDetails"] = "Ki\u015fisel bilgilerinizi g\u00fcncelleyin",

            // City Search
            ["SelectCity"]            = "\u015eehir Se\u00e7",
            ["SearchCityHint"]        = "\u015eehir ad\u0131 yaz\u0131n\u2026",
            ["UseCurrentLocation"]    = "Mevcut Konumu Kullan",
            ["NoResults"]             = "Sonu\u00e7 bulunamad\u0131",

            // No Location Page
            ["NoLocationTitle"]       = "Konum Ayarlanmad\u0131",
            ["NoLocationDesc"]        = "Devam etmek i\u00e7in konum izni verin — veya a\u015fa\u011f\u0131dan \u015fehrinizi se\u00e7in.",
            ["Or"]                    = "veya",
            ["OpenSettings"]          = "Ayarlar\u0131 A\u00e7",
            ["LocationPermission"]    = "Konum \u0130zni",
            ["LocationPermDenied"]    = "Konum eri\u015fimi reddedildi. L\u00fctfen cihaz Ayarlar\u0131ndan etkinle\u015ftirin.",

            // Calculation method
            ["CalcMethod"]            = "Hesaplama Yöntemi",
            ["CalcMethodDiyanet"]     = "Diyanet",
            ["CalcMethodQMI"]         = "Kafkasya Müslümanları İdaresi",

            // Qibla
            ["QiblaInstruction"]      = "Cihazı düz bir yüzeye koyun, sonra hareket ettirin",

            // Notifications
            ["Notif_Title"]           = "Namaz Vakti",
            ["Notif_BeforeBody"]      = "{0} namazına {1} dakika kaldı",
            ["Notif_BeforeBody_H"]    = "{0} namazına {1} saat {2} dakika kaldı",
            ["Notif_OnBody"]          = "{0} namazı girdi",
            ["Notif_EndsBody"]        = "{0} namazının bitmesine {1} dakika kaldı",
            ["Notif_EndsBody_H"]      = "{0} namazının bitmesine {1} saat {2} dakika kaldı",
            ["AppliesToAll"]          = "Tüm namaz vakitlerine uygulanır",
            ["CustomizePerPrayer"]    = "Her namaz için özelleştir",

            // Settings page UI
            ["Sett_Before"]          = "Vakitten Önce",
            ["Sett_On"]              = "Namaz Vaktinde",
            ["Sett_Ends"]            = "Vaktin Bitmesine",
            ["Sett_SoundAdhan"]      = "Ses",
            ["Sett_PlayNow"]         = "Sesi Şimdi Çal",
            ["Sett_PlayNowDesc"]     = "Ses direkt çalınır — bildirim gerekmez",
            ["Sett_TestNotif"]       = "Test Bildirimi",
            ["Sett_TestNotifDesc"]   = "10 sn sonra ateşlenir — ana ekrana git",
            ["Sett_ViewLog"]         = "Bildirim Günlüğü",
            ["Sett_ViewLogDesc"]     = "Günlüğü görüntülemek için dokun",
            ["Sett_SelectSound"]     = "Ses Seçin",
            ["Sett_PlayWhich"]       = "Hangi ses çalınsın?",
            ["Sett_TestWhich"]       = "Hangi ses ile test edilsin?",
            ["Sett_TestAlarmTitle"]  = "Test Alarmı Kuruldu",
            ["Sett_TestAlarmBody"]   = "Ses: {0}\n10 saniye içinde çalınır.\n\n1. Tamam'a dokun\n2. Ana ekrana git\n3. Bildirimi bekle",
            ["Sett_LogTitle"]        = "Bildirim Günlüğü (Kopyalandı!)",
            ["Sett_LogClearedTitle"] = "Günlük Temizlendi",
            ["Sett_LogClearedBody"]  = "Günlük dosyası temizlendi.",
            ["Cancel"]               = "İptal",
            ["OK"]                   = "Tamam",

            // Calculation method names
            ["CalcMethod_0"]         = "Shia Ithna-Ansari",
            ["CalcMethod_1"]         = "University of Islamic Sciences, Karachi",
            ["CalcMethod_2"]         = "Islamic Society of North America (ISNA)",
            ["CalcMethod_3"]         = "Muslim World League (MWL)",
            ["CalcMethod_4"]         = "Umm Al-Qura University, Makkah",
            ["CalcMethod_5"]         = "Egyptian General Authority of Survey",
            ["CalcMethod_7"]         = "Institute of Geophysics, University of Tehran",
            ["CalcMethod_8"]         = "Gulf Region",
            ["CalcMethod_9"]         = "Kuwait",
            ["CalcMethod_10"]        = "Qatar",
            ["CalcMethod_11"]        = "Majlis Ugama Islam Singapura (MUIS)",
            ["CalcMethod_12"]        = "Union Organization Islamic de France",
            ["CalcMethod_13"]        = "Diyanet \u0130\u015fleri Ba\u015fkanl\u0131\u011f\u0131, Turkey",
            ["CalcMethod_14"]        = "Spiritual Administration of Muslims of Russia",
            ["CalcMethod_15"]        = "Moonsighting Committee Worldwide (Khalid Shaukat)",
            ["CalcMethod_16"]        = "Dubai",
            ["CalcMethod_17"]        = "Jabatan Kemajuan Islam Malaysia (JAKIM)",
            ["CalcMethod_18"]        = "Jordan",
            ["CalcMethod_19"]        = "Islamic University of Madinah",
            ["CalcMethod_20"]        = "Kementerian Agama Republik Indonesia",
            ["CalcMethod_21"]        = "Morocco",
            ["CalcMethod_22"]        = "Comunidade Islamica de Lisboa",
            ["CalcMethod_23"]        = "Ministry of Awqaf and Islamic Affairs, Algeria",
            ["CalcMethod_24"]        = "Kafkasya M\u00fcsl\u00fcmanlar\u0131 \u0130daresi",
            ["CalcMethod_99"]        = "\u00d6zel",

            // Calc config page
            ["CalcConfig_Title"]      = "Hesaplama Parametreleri",
            ["CalcConfig_Shafaq"]     = "\u015eafak (Alacakaranl\u0131k)",
            ["CalcConfig_ShafaqDesc"] = "Yats\u0131 hesab\u0131nda kullan\u0131lan alacakaranl\u0131k t\u00fcr\u00fc",
            ["CalcConfig_Tune"]       = "Ayar (Dakika Farklar\u0131)",
            ["CalcConfig_TuneDesc"]   = "Her namaz i\u00e7in dakika cinsinden virg\u00fclle ayr\u0131lm\u0131\u015f farklar",
            ["CalcConfig_School"]     = "F\u0131khi Mezhep (\u0130kindi)",
            ["CalcConfig_Midnight"]   = "Gece Yar\u0131s\u0131 Modu",
            ["CalcConfig_LatAdj"]     = "Enlem Ayar\u0131",
            ["CalcConfig_Calendar"]   = "Takvim Y\u00f6ntemi",
            ["CalcConfig_Apply"]      = "Uygula",
            ["CalcConfig_Reset"]      = "Varsay\u0131lana S\u0131f\u0131rla",
            ["Shafaq_General"]        = "Genel",
            ["Shafaq_Ahmer"]          = "Ahmer (K\u0131rm\u0131z\u0131)",
            ["Shafaq_Abyad"]          = "Abyad (Beyaz)",
            ["School_Shafi"]          = "\u015eafii / Standart",
            ["School_Hanafi"]         = "Hanefi",
            ["Midnight_Standard"]     = "Standart (G\u00fcnbat\u0131m\u0131-Do\u011fum Ortas\u0131)",
            ["Midnight_Jafari"]       = "Caferi (G\u00fcnbat\u0131m\u0131-Fecir Ortas\u0131)",
            ["LatAdj_None"]           = "Ayar Yok",
            ["LatAdj_Middle"]         = "Gecenin Ortas\u0131",
            ["LatAdj_Seventh"]        = "Gecenin Yedide Biri",
            ["LatAdj_Angle"]          = "A\u00e7\u0131 Tabanl\u0131",
            ["Calendar_HJCoSA"]       = "Hicri (HJCoSA)",
            ["Calendar_UAQ"]          = "\u00dcmm\u00fc'l-Kura (UAQ)",
            ["Calendar_DIYANET"]      = "Diyanet",
            ["Calendar_MATHEMATICAL"] = "Matematiksel",
        },

        ["az"] = new()
        {
            // Tabs
            ["Tab_Home"]              = "ANA S\u018fH\u0130F\u018f",
            ["Tab_Monthly"]           = "VAXTLAR",
            ["Tab_Qibla"]             = "Q\u0130BL\u018f",
            ["Tab_Quran"]             = "QURAN",
            ["Tab_Settings"]          = "AYARLAR",

            // Main Page
            ["Greeting"]              = "\u018fssalamu \u018fleykum",
            ["FastDay"]               = "Oruc G\u00fcn\u00fc",
            ["UpcomingPrayer"]        = "YAXINLA\u015eAN NAMAZ",
            ["Time"]                  = "VAXT",
            ["StartsIn"]              = "BA\u015eLAYIR",
            ["Hrs"]                   = "SAAT",
            ["Min"]                   = "DƏQİQƏ",
            ["Sec"]                   = "SANİYƏ",
            ["Local"]                 = "YERLI",
            //["CurrentPrayer"]         = "CAR\u0130 NAMAZ",
            ["NextIn"]                = "VAXTIN ÇIXMASINA",
            ["DailyTimes"]            = "G\u00fcnl\u00fck Vaxtlar",
            ["MonthlyTable"]          = "Ayl\u0131q C\u0259dv\u0259l",

            // Prayer names
            ["Prayer_Fajr"]           = "Sübh",
            ["Prayer_Sunrise"]        = "Gün çıxır",
            ["Prayer_Dhuhr"]          = "Zöhr",
            ["Prayer_Asr"]            = "Əsr",
            ["Prayer_Maghrib"]        = "Məğrib",
            ["Prayer_Isha"]           = "İşa",

            // Monthly Page
            ["MonthlySchedule"]       = "Ayl\u0131q Namaz Vaxtları",
            ["Date"]                  = "Gün",
            ["BenefitOfMonth"]        = "AYIN FAYDASI",
            ["BenefitQuote"]          = "\u201cBe\u015fd\u0259n \u0259vv\u0259l be\u015fd\u0259n istifad\u0259 et: qocal\u0131\u011f\u0131ndan \u0259vv\u0259l g\u0259ncliyin, x\u0259st\u0259liyind\u0259n \u0259vv\u0259l sa\u011flaml\u0131\u011f\u0131n...\u201d",
            ["BenefitAttribution"]    = "\u2014 H\u0259dis, \u018fl-Hakim",

            // Qibla / Quran
            ["Qibla"]                 = "Qibl\u0259",
            ["Quran"]                 = "Quran",
            ["ComingSoon"]            = "Tezlikl\u0259",

            // Settings
            ["Settings"]              = "T\u0259nziml\u0259m\u0259l\u0259r",
            ["AppLanguage"]           = "T\u0259tbiq Dili",
            ["SelectLanguage"]        = "Dil seçin",
            ["Change"]                = "D\u018fY\u0130\u015eD\u0130R",
            ["LocationThreshold"]     = "Konum Yenilm\u0259 H\u0259ddi",
            ["LocationThresholdDesc"] = "Bu m\u0259saf\u0259d\u0259n sonra \u015f\u0259h\u0259r d\u0259yi\u015fs\u0259 namaz vaxtlar\u0131 yenid\u0259n al\u0131n\u0131r",
            ["NotificationsAndPrefs"] = "B\u0130LD\u0130R\u0130\u015eL\u018fR V\u018f T\u018fRC\u0130HL\u018fR",
            ["PrayerNotifications"]   = "Namaz Bildiri\u015fl\u0259ri",
            ["DarkMode"]              = "Qaranl\u0131q Rejim",
            ["LocationServices"]      = "M\u0259kan Xidm\u0259tl\u0259ri",
            ["CalculationMethod"]     = "HESABLAMA \u00dcSULU",
            ["FajrIshaMethod"]        = "Hesablama \u00dcsulu",
            ["MuslimWorldLeague"]     = "Türkiyə Diyanet İşleri Başkanlığı",
            ["Account"]               = "HESAB",
            ["ProfileInformation"]    = "Profil M\u0259lumat\u0131",
            ["UpdatePersonalDetails"] = "\u015e\u0259xsi m\u0259lumatlar\u0131n\u0131z\u0131 yeniley\u0259n",

            // City Search
            ["SelectCity"]            = "\u015e\u0259h\u0259r Se\u00e7",
            ["SearchCityHint"]        = "\u015e\u0259h\u0259r ad\u0131 yaz\u0131n\u2026",
            ["UseCurrentLocation"]    = "M\u0259vcut Yeri \u0130stifad\u0259 Et",
            ["NoResults"]             = "N\u0259tic\u0259 tapilmad\u0131",

            // No Location Page
            ["NoLocationTitle"]       = "M\u0259kan T\u0259yin Edilm\u0259yib",
            ["NoLocationDesc"]        = "Davam etm\u0259k \u00fc\u00e7\u00fcn m\u0259kan ic\u0259z\u0259si verin — ya da a\u015fa\u011f\u0131dan \u015f\u0259h\u0259rinizi se\u00e7in.",
            ["Or"]                    = "v\u0259 ya",
            ["OpenSettings"]          = "Parametrl\u0259ri A\u00e7",
            ["LocationPermission"]    = "M\u0259kan \u0130c\u0259z\u0259si",
            ["LocationPermDenied"]    = "M\u0259kan giri\u015fi r\u0259dd edildi. Z\u0259hm\u0259t olmasa cihaz Parametrl\u0259rind\u0259n aktivl\u0259\u015fdirin.",

            // Calculation method
            ["CalcMethod"]            = "Hesablama Metodu",
            ["CalcMethodDiyanet"]     = "Diyanet",
            ["CalcMethodQMI"]         = "Qafqaz Müsəlmanları İdarəsi",

            // Qibla
            ["QiblaInstruction"]      = "Cihazı düz bir səthin üzərinə qoyun, sonra hərəkət etdirin",

            // Notifications
            ["Notif_Title"]           = "Namaz Vaxtı",
            ["Notif_BeforeBody"]      = "{0} namazına {1} dəqiqə qalıb",
            ["Notif_BeforeBody_H"]    = "{0} namazına {1} saat {2} dəqiqə qalıb",
            ["Notif_OnBody"]          = "{0} namazı girdi",
            ["Notif_EndsBody"]        = "{0} namazının çıxmasına {1} dəqiqə qalıb",
            ["Notif_EndsBody_H"]      = "{0} namazının çıxmasına {1} saat {2} dəqiqə qalıb",
            ["AppliesToAll"]          = "Bütün namaz vaxtlarına tətbiq edilir",
            ["CustomizePerPrayer"]    = "Hər namaz üçün fərdiləşdir",

            // Settings page UI
            ["Sett_Before"]          = "Namazdan Əvvəl",
            ["Sett_On"]              = "Namaz Vaxtında",
            ["Sett_Ends"]            = "Vaxtın Bitməsinə",
            ["Sett_SoundAdhan"]      = "Səs",
            ["Sett_PlayNow"]         = "Səsi İndi Çal",
            ["Sett_PlayNowDesc"]     = "Səs birbaşa çalınır — bildiriş lazım deyil",
            ["Sett_TestNotif"]       = "Test Bildirişi",
            ["Sett_TestNotifDesc"]   = "10 san. sonra işə düşür — ana ekrana keç",
            ["Sett_ViewLog"]         = "Bildiriş Jurnalı",
            ["Sett_ViewLogDesc"]     = "Jurnalı görmək üçün toxun",
            ["Sett_SelectSound"]     = "Səs Seçin",
            ["Sett_PlayWhich"]       = "Hansı səs çalınsın?",
            ["Sett_TestWhich"]       = "Hansı səslə test edilsin?",
            ["Sett_TestAlarmTitle"]  = "Test Siqnalı Quruldu",
            ["Sett_TestAlarmBody"]   = "Səs: {0}\n10 saniyə sonra çalınacaq.\n\n1. OK düyməsinə toxun\n2. Ana ekrana keç\n3. Bildirişi gözlə",
            ["Sett_LogTitle"]        = "Bildiriş Jurnalı (Kopyalandı!)",
            ["Sett_LogClearedTitle"] = "Jurnal Təmizləndi",
            ["Sett_LogClearedBody"]  = "Jurnal faylı təmizləndi.",
            ["Cancel"]               = "Ləğv et",
            ["OK"]                   = "Tamam",

            // Calculation method names
            ["CalcMethod_0"]         = "Shia Ithna-Ansari",
            ["CalcMethod_1"]         = "University of Islamic Sciences, Karachi",
            ["CalcMethod_2"]         = "Islamic Society of North America (ISNA)",
            ["CalcMethod_3"]         = "Muslim World League (MWL)",
            ["CalcMethod_4"]         = "Umm Al-Qura University, Makkah",
            ["CalcMethod_5"]         = "Egyptian General Authority of Survey",
            ["CalcMethod_7"]         = "Institute of Geophysics, University of Tehran",
            ["CalcMethod_8"]         = "Gulf Region",
            ["CalcMethod_9"]         = "Kuwait",
            ["CalcMethod_10"]        = "Qatar",
            ["CalcMethod_11"]        = "Majlis Ugama Islam Singapura (MUIS)",
            ["CalcMethod_12"]        = "Union Organization Islamic de France",
            ["CalcMethod_13"]        = "Diyanet \u0130\u015fleri Ba\u015fkanl\u0131\u011f\u0131, T\u00fcrkiy\u0259",
            ["CalcMethod_14"]        = "Spiritual Administration of Muslims of Russia",
            ["CalcMethod_15"]        = "Moonsighting Committee Worldwide (Khalid Shaukat)",
            ["CalcMethod_16"]        = "Dubai",
            ["CalcMethod_17"]        = "Jabatan Kemajuan Islam Malaysia (JAKIM)",
            ["CalcMethod_18"]        = "Jordan",
            ["CalcMethod_19"]        = "Islamic University of Madinah",
            ["CalcMethod_20"]        = "Kementerian Agama Republik Indonesia",
            ["CalcMethod_21"]        = "Morocco",
            ["CalcMethod_22"]        = "Comunidade Islamica de Lisboa",
            ["CalcMethod_23"]        = "Ministry of Awqaf and Islamic Affairs, Algeria",
            ["CalcMethod_24"]        = "Qafqaz M\u00fcs\u0259lmanlar\u0131 \u0130dar\u0259si",
            ["CalcMethod_99"]        = "X\u00fcsusi",

            // Calc config page
            ["CalcConfig_Title"]      = "Hesablama Parametrl\u0259ri",
            ["CalcConfig_Shafaq"]     = "\u015e\u0259f\u0259q (Alatoqanl\u0131q)",
            ["CalcConfig_ShafaqDesc"] = "\u0130\u015fa hesab\u0131nda istifad\u0259 olunan alatoqanl\u0131q n\u00f6v\u00fc",
            ["CalcConfig_Tune"]       = "T\u0259nzim (D\u0259qiq\u0259 F\u0259rql\u0259ri)",
            ["CalcConfig_TuneDesc"]   = "H\u0259r namaz \u00fc\u00e7\u00fcn verg\u00fcll\u0259 ayr\u0131lm\u0131\u015f d\u0259qiq\u0259 f\u0259rql\u0259ri",
            ["CalcConfig_School"]     = "Fiqh M\u0259zh\u0259bi (\u018fsr)",
            ["CalcConfig_Midnight"]   = "Gec\u0259yar\u0131s\u0131 Rejimi",
            ["CalcConfig_LatAdj"]     = "Enlik T\u0259nzimat\u0131",
            ["CalcConfig_Calendar"]   = "T\u0259qvim \u00dcsutu",
            ["CalcConfig_Apply"]      = "T\u0259tbiq et",
            ["CalcConfig_Reset"]      = "Standarta S\u0131f\u0131rla",
            ["Shafaq_General"]        = "\u00dcmumi",
            ["Shafaq_Ahmer"]          = "\u018fhm\u0259r (Q\u0131rm\u0131z\u0131)",
            ["Shafaq_Abyad"]          = "\u018fbyad (A\u011f)",
            ["School_Shafi"]          = "\u015eafii / Standart",
            ["School_Hanafi"]         = "H\u0259n\u0259fi",
            ["Midnight_Standard"]     = "Standart (G\u00fcnbat\u0131m\u0131-Do\u011fum Ortas\u0131)",
            ["Midnight_Jafari"]       = "C\u0259f\u0259ri (G\u00fcnbat\u0131m\u0131-F\u0259cr Ortas\u0131)",
            ["LatAdj_None"]           = "T\u0259nzimat Yoxdur",
            ["LatAdj_Middle"]         = "Gec\u0259nin Ortas\u0131",
            ["LatAdj_Seventh"]        = "Gec\u0259nin Yeddid\u0259 Biri",
            ["LatAdj_Angle"]          = "Bucaq \u018fsasl\u0131",
            ["Calendar_HJCoSA"]       = "Hicri (HJCoSA)",
            ["Calendar_UAQ"]          = "\u00dcmm\u00fc'l-Qura (UAQ)",
            ["Calendar_DIYANET"]      = "Diyanet",
            ["Calendar_MATHEMATICAL"] = "Riyazi",
        },

        ["ru"] = new()
        {
            ["Tab_Home"]              = "ГЛАВНАЯ",
            ["Tab_Monthly"]           = "РАСПИСАНИЕ",
            ["Tab_Qibla"]             = "КИБЛА",
            ["Tab_Quran"]             = "КОРАН",
            ["Tab_Settings"]          = "НАСТРОЙКИ",
            ["Greeting"]              = "Ассаляму Алейкум",
            ["FastDay"]               = "День поста",
            ["UpcomingPrayer"]        = "СЛЕДУЮЩИЙ НАМАЗ",
            ["Time"]                  = "ВРЕМЯ",
            ["StartsIn"]              = "НАЧАЛО",
            ["Hrs"]                   = "ЧАСЫ",
            ["Min"]                   = "МИНУТЫ",
            ["Sec"]                   = "СЕКУНДЫ",
            ["Local"]                 = "МЕСТНОЕ",
            ["NextIn"]                = "ДО КОНЦА НАМАЗА",
            ["DailyTimes"]            = "Дневные времена",
            ["MonthlyTable"]          = "Ежемесячная таблица",
            ["Prayer_Fajr"]           = "Фаджр",
            ["Prayer_Sunrise"]        = "Восход",
            ["Prayer_Dhuhr"]          = "Зухр",
            ["Prayer_Asr"]            = "Аср",
            ["Prayer_Maghrib"]        = "Магриб",
            ["Prayer_Isha"]           = "Иша",
            ["MonthlySchedule"]       = "Ежемесячное расписание намазов",
            ["Date"]                  = "День",
            ["BenefitOfMonth"]        = "ПОЛЬЗА МЕСЯЦА",
            ["BenefitQuote"]          = "\u00abИспользуй пять до пяти: молодость до старости, здоровье до болезни...\u00bb",
            ["BenefitAttribution"]    = "\u2014 Хадис, Аль-Хаким",
            ["Qibla"]                 = "Кибла",
            ["Quran"]                 = "Коран",
            ["ComingSoon"]            = "Скоро",
            ["Settings"]              = "Настройки",
            ["AppLanguage"]           = "Язык приложения",
            ["SelectLanguage"]        = "Выберите язык",
            ["Change"]                = "ИЗМЕНИТЬ",
            ["LocationThreshold"]     = "Порог обновления локации",
            ["LocationThresholdDesc"] = "Обновлять время намаза, если город изменился после перемещения на это расстояние",
            ["NotificationsAndPrefs"] = "УВЕДОМЛЕНИЯ И НАСТРОЙКИ",
            ["PrayerNotifications"]   = "Уведомления о намазе",
            ["DarkMode"]              = "Тёмный режим",
            ["LocationServices"]      = "Службы геолокации",
            ["CalculationMethod"]     = "МЕТОД РАСЧЁТА",
            ["FajrIshaMethod"]        = "Метод расчёта",
            ["MuslimWorldLeague"]     = "Президиум по религиозным делам (Турция)",
            ["Account"]               = "АККАУНТ",
            ["ProfileInformation"]    = "Информация профиля",
            ["UpdatePersonalDetails"] = "Обновите личные данные",
            ["SelectCity"]            = "Выбрать город",
            ["SearchCityHint"]        = "Введите название города\u2026",
            ["UseCurrentLocation"]    = "Использовать текущее местоположение",
            ["NoResults"]             = "Результаты не найдены",
            ["CalcMethod"]            = "Метод расчёта",
            ["CalcMethodDiyanet"]     = "Diyanet",
            ["CalcMethodQMI"]         = "Управление мусульман Кавказа",
            ["QiblaInstruction"]      = "Положите устройство на ровную поверхность и двигайте его",
            ["Notif_Title"]           = "Время намаза",
            ["Notif_BeforeBody"]      = "{0} через {1} мин",
            ["Notif_BeforeBody_H"]    = "{0} через {1}ч {2}мин",
            ["Notif_OnBody"]          = "Намаз {0} начался",
            ["Notif_EndsBody"]        = "{0} заканчивается через {1} мин",
            ["Notif_EndsBody_H"]      = "{0} заканчивается через {1}ч {2}мин",
            ["AppliesToAll"]          = "Применяется ко всем намазам",
            ["CustomizePerPrayer"]    = "Настройка для каждого намаза",
            ["Sett_Before"]          = "До намаза",
            ["Sett_On"]              = "Во время намаза",
            ["Sett_Ends"]            = "До конца намаза",
            ["Sett_SoundAdhan"]      = "Звук",
            ["Sett_PlayNow"]         = "Воспроизвести сейчас",
            ["Sett_PlayNowDesc"]     = "Звук воспроизводится напрямую — уведомление не нужно",
            ["Sett_TestNotif"]       = "Тестовое уведомление",
            ["Sett_TestNotifDesc"]   = "Сработает через 10 сек — перейдите на главный экран",
            ["Sett_ViewLog"]         = "Журнал уведомлений",
            ["Sett_ViewLogDesc"]     = "Нажмите для просмотра журнала",
            ["Sett_SelectSound"]     = "Выберите звук",
            ["Sett_PlayWhich"]       = "Какой звук воспроизвести?",
            ["Sett_TestWhich"]       = "Какой звук использовать для теста?",
            ["Sett_TestAlarmTitle"]  = "Тестовый сигнал установлен",
            ["Sett_TestAlarmBody"]   = "Звук: {0}\nСработает через 10 секунд.\n\n1. Нажмите OK\n2. Перейдите на главный экран\n3. Ожидайте уведомление",
            ["Sett_LogTitle"]        = "Журнал уведомлений (Скопировано!)",
            ["Sett_LogClearedTitle"] = "Журнал очищен",
            ["Sett_LogClearedBody"]  = "Файл журнала очищен.",
            ["Cancel"]               = "Отмена",
            ["OK"]                   = "OK",

            // Calculation method names
            ["CalcMethod_0"]         = "Shia Ithna-Ansari",
            ["CalcMethod_1"]         = "University of Islamic Sciences, Karachi",
            ["CalcMethod_2"]         = "Islamic Society of North America (ISNA)",
            ["CalcMethod_3"]         = "Muslim World League (MWL)",
            ["CalcMethod_4"]         = "Umm Al-Qura University, Makkah",
            ["CalcMethod_5"]         = "Egyptian General Authority of Survey",
            ["CalcMethod_7"]         = "Institute of Geophysics, University of Tehran",
            ["CalcMethod_8"]         = "Gulf Region",
            ["CalcMethod_9"]         = "Kuwait",
            ["CalcMethod_10"]        = "Qatar",
            ["CalcMethod_11"]        = "Majlis Ugama Islam Singapura (MUIS)",
            ["CalcMethod_12"]        = "Union Organization Islamic de France",
            ["CalcMethod_13"]        = "\u0423\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u0438\u0435 \u043f\u043e \u0434\u0435\u043b\u0430\u043c \u0440\u0435\u043b\u0438\u0433\u0438\u0438, \u0422\u0443\u0440\u0446\u0438\u044f",
            ["CalcMethod_14"]        = "\u0414\u0443\u0445\u043e\u0432\u043d\u043e\u0435 \u0443\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u0438\u0435 \u043c\u0443\u0441\u0443\u043b\u044c\u043c\u0430\u043d \u0420\u043e\u0441\u0441\u0438\u0438",
            ["CalcMethod_15"]        = "Moonsighting Committee Worldwide (Khalid Shaukat)",
            ["CalcMethod_16"]        = "Dubai",
            ["CalcMethod_17"]        = "Jabatan Kemajuan Islam Malaysia (JAKIM)",
            ["CalcMethod_18"]        = "Jordan",
            ["CalcMethod_19"]        = "Islamic University of Madinah",
            ["CalcMethod_20"]        = "Kementerian Agama Republik Indonesia",
            ["CalcMethod_21"]        = "Morocco",
            ["CalcMethod_22"]        = "Comunidade Islamica de Lisboa",
            ["CalcMethod_23"]        = "Ministry of Awqaf and Islamic Affairs, Algeria",
            ["CalcMethod_24"]        = "\u0423\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u0438\u0435 \u043c\u0443\u0441\u0443\u043b\u044c\u043c\u0430\u043d \u041a\u0430\u0432\u043a\u0430\u0437\u0430",
            ["CalcMethod_99"]        = "\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c\u0441\u043a\u0438\u0439",

            // Calc config page
            ["CalcConfig_Title"]      = "\u041f\u0430\u0440\u0430\u043c\u0435\u0442\u0440\u044b \u0440\u0430\u0441\u0447\u0451\u0442\u0430",
            ["CalcConfig_Shafaq"]     = "\u0428\u0430\u0444\u0430\u043a (\u0421\u0443\u043c\u0435\u0440\u043a\u0438)",
            ["CalcConfig_ShafaqDesc"] = "\u0422\u0438\u043f \u0441\u0443\u043c\u0435\u0440\u0435\u043a \u0434\u043b\u044f \u0440\u0430\u0441\u0447\u0451\u0442\u0430 \u0418\u0448\u0430",
            ["CalcConfig_Tune"]       = "\u041d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0430 (\u0441\u043c\u0435\u0449\u0435\u043d\u0438\u0435 \u0432 \u043c\u0438\u043d\u0443\u0442\u0430\u0445)",
            ["CalcConfig_TuneDesc"]   = "\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u044f \u0441\u043c\u0435\u0449\u0435\u043d\u0438\u044f \u0432 \u043c\u0438\u043d\u0443\u0442\u0430\u0445 \u0447\u0435\u0440\u0435\u0437 \u0437\u0430\u043f\u044f\u0442\u0443\u044e \u0434\u043b\u044f \u043a\u0430\u0436\u0434\u043e\u0433\u043e \u043d\u0430\u043c\u0430\u0437\u0430",
            ["CalcConfig_School"]     = "\u041f\u0440\u0430\u0432\u043e\u0432\u0430\u044f \u0448\u043a\u043e\u043b\u0430 (\u0410\u0441\u0440)",
            ["CalcConfig_Midnight"]   = "\u0420\u0435\u0436\u0438\u043c \u043f\u043e\u043b\u0443\u043d\u043e\u0447\u0438",
            ["CalcConfig_LatAdj"]     = "\u041a\u043e\u0440\u0440\u0435\u043a\u0442\u0438\u0440\u043e\u0432\u043a\u0430 \u0448\u0438\u0440\u043e\u0442\u044b",
            ["CalcConfig_Calendar"]   = "\u041c\u0435\u0442\u043e\u0434 \u043a\u0430\u043b\u0435\u043d\u0434\u0430\u0440\u044f",
            ["CalcConfig_Apply"]      = "\u041f\u0440\u0438\u043c\u0435\u043d\u0438\u0442\u044c",
            ["CalcConfig_Reset"]      = "\u0421\u0431\u0440\u043e\u0441 \u0434\u043e \u0443\u043c\u043e\u043b\u0447\u0430\u043d\u0438\u0439",
            ["Shafaq_General"]        = "\u041e\u0431\u0449\u0438\u0439",
            ["Shafaq_Ahmer"]          = "\u0410\u0445\u043c\u0435\u0440 (\u041a\u0440\u0430\u0441\u043d\u044b\u0439)",
            ["Shafaq_Abyad"]          = "\u0410\u0431\u044c\u044f\u0434 (\u0411\u0435\u043b\u044b\u0439)",
            ["School_Shafi"]          = "\u0428\u0430\u0444\u0438\u0438 / \u0421\u0442\u0430\u043d\u0434\u0430\u0440\u0442",
            ["School_Hanafi"]         = "\u0425\u0430\u043d\u0430\u0444\u0438",
            ["Midnight_Standard"]     = "\u0421\u0442\u0430\u043d\u0434\u0430\u0440\u0442 (\u0441\u0435\u0440\u0435\u0434\u0438\u043d\u0430 \u0437\u0430\u043a\u0430\u0442\u0430-\u0432\u043e\u0441\u0445\u043e\u0434\u0430)",
            ["Midnight_Jafari"]       = "\u0414\u0436\u0430\u0444\u0430\u0440\u0438 (\u0441\u0435\u0440\u0435\u0434\u0438\u043d\u0430 \u0437\u0430\u043a\u0430\u0442\u0430-\u0444\u0430\u0434\u0436\u0440\u0430)",
            ["LatAdj_None"]           = "\u0411\u0435\u0437 \u043a\u043e\u0440\u0440\u0435\u043a\u0442\u0438\u0440\u043e\u0432\u043a\u0438",
            ["LatAdj_Middle"]         = "\u0421\u0435\u0440\u0435\u0434\u0438\u043d\u0430 \u043d\u043e\u0447\u0438",
            ["LatAdj_Seventh"]        = "\u041e\u0434\u043d\u0430 \u0441\u0435\u0434\u044c\u043c\u0430\u044f \u043d\u043e\u0447\u0438",
            ["LatAdj_Angle"]          = "\u041d\u0430 \u043e\u0441\u043d\u043e\u0432\u0435 \u0443\u0433\u043b\u0430",
            ["Calendar_HJCoSA"]       = "\u0425\u0438\u0434\u0436\u0440\u0438 (HJCoSA)",
            ["Calendar_UAQ"]          = "\u0423\u043c\u043c \u0430\u043b\u044c-\u041a\u0443\u0440\u0430 (UAQ)",
            ["Calendar_DIYANET"]      = "\u0414\u0438\u0430\u043d\u0435\u0442",
            ["Calendar_MATHEMATICAL"] = "\u041c\u0430\u0442\u0435\u043c\u0430\u0442\u0438\u0447\u0435\u0441\u043a\u0438\u0439",

            ["NoLocationTitle"]       = "Местоположение не задано",
            ["NoLocationDesc"]        = "Для продолжения предоставьте разрешение на геолокацию — или выберите город ниже.",
            ["Or"]                    = "или",
            ["OpenSettings"]          = "Открыть настройки",
            ["LocationPermission"]    = "Разрешение на геолокацию",
            ["LocationPermDenied"]    = "Доступ к геолокации запрещён. Пожалуйста, включите его в настройках устройства.",
        },

        ["ar"] = new()
        {
            ["Tab_Home"]              = "الرئيسية",
            ["Tab_Monthly"]           = "الجدول الشهري",
            ["Tab_Qibla"]             = "القبلة",
            ["Tab_Quran"]             = "القرآن",
            ["Tab_Settings"]          = "الإعدادات",
            ["Greeting"]              = "السلام عليكم",
            ["FastDay"]               = "يوم الصيام",
            ["UpcomingPrayer"]        = "الصلاة القادمة",
            ["Time"]                  = "الوقت",
            ["StartsIn"]              = "يبدأ في",
            ["Hrs"]                   = "ساعات",
            ["Min"]                   = "دقائق",
            ["Sec"]                   = "ثواني",
            ["Local"]                 = "المحلي",
            ["NextIn"]                = "ينتهي في",
            ["DailyTimes"]            = "أوقات اليوم",
            ["MonthlyTable"]          = "الجدول الشهري",
            ["Prayer_Fajr"]           = "الفجر",
            ["Prayer_Sunrise"]        = "الشروق",
            ["Prayer_Dhuhr"]          = "الظهر",
            ["Prayer_Asr"]            = "العصر",
            ["Prayer_Maghrib"]        = "المغرب",
            ["Prayer_Isha"]           = "العشاء",
            ["MonthlySchedule"]       = "مواقيت الصلاة الشهرية",
            ["Date"]                  = "اليوم",
            ["BenefitOfMonth"]        = "فائدة الشهر",
            ["BenefitQuote"]          = "\u00abاغتنم خمساً قبل خمس: شبابك قبل هرمك، وصحتك قبل سقمك...\u00bb",
            ["BenefitAttribution"]    = "\u2014 حديث، الحاكم",
            ["Qibla"]                 = "القبلة",
            ["Quran"]                 = "القرآن",
            ["ComingSoon"]            = "قريباً",
            ["Settings"]              = "الإعدادات",
            ["AppLanguage"]           = "لغة التطبيق",
            ["SelectLanguage"]        = "اختر اللغة",
            ["Change"]                = "تغيير",
            ["LocationThreshold"]     = "حد تحديث الموقع",
            ["LocationThresholdDesc"] = "إعادة جلب أوقات الصلاة عند تغيير المدينة بعد هذه المسافة",
            ["NotificationsAndPrefs"] = "الإشعارات والتفضيلات",
            ["PrayerNotifications"]   = "إشعارات الصلاة",
            ["DarkMode"]              = "الوضع الداكن",
            ["LocationServices"]      = "خدمات الموقع",
            ["CalculationMethod"]     = "طريقة الحساب",
            ["FajrIshaMethod"]        = "طريقة الحساب",
            ["MuslimWorldLeague"]     = "رئاسة الشؤون الدينية (تركيا)",
            ["Account"]               = "الحساب",
            ["ProfileInformation"]    = "معلومات الملف الشخصي",
            ["UpdatePersonalDetails"] = "تحديث بياناتك الشخصية",
            ["SelectCity"]            = "اختر مدينة",
            ["SearchCityHint"]        = "اكتب اسم المدينة\u2026",
            ["UseCurrentLocation"]    = "استخدم الموقع الحالي",
            ["NoResults"]             = "لا توجد نتائج",
            ["CalcMethod"]            = "طريقة الحساب",
            ["CalcMethodDiyanet"]     = "ديانت",
            ["CalcMethodQMI"]         = "إدارة مسلمي القوقاز",
            ["QiblaInstruction"]      = "ضع جهازك على سطح مستوٍ ثم حرّكه",
            ["Notif_Title"]           = "وقت الصلاة",
            ["Notif_BeforeBody"]      = "{0} بعد {1} دقيقة",
            ["Notif_BeforeBody_H"]    = "{0} بعد {1} ساعة و{2} دقيقة",
            ["Notif_OnBody"]          = "حانت صلاة {0}",
            ["Notif_EndsBody"]        = "ينتهي وقت {0} بعد {1} دقيقة",
            ["Notif_EndsBody_H"]      = "ينتهي وقت {0} بعد {1} ساعة و{2} دقيقة",
            ["AppliesToAll"]          = "ينطبق على جميع الصلوات",
            ["CustomizePerPrayer"]    = "تخصيص لكل صلاة",
            ["Sett_Before"]          = "قبل وقت الصلاة",
            ["Sett_On"]              = "عند وقت الصلاة",
            ["Sett_Ends"]            = "قبل انتهاء وقت الصلاة",
            ["Sett_SoundAdhan"]      = "صوت",
            ["Sett_PlayNow"]         = "تشغيل الآن",
            ["Sett_PlayNowDesc"]     = "يُشغّل الصوت مباشرة — لا حاجة لإشعار",
            ["Sett_TestNotif"]       = "إشعار تجريبي",
            ["Sett_TestNotifDesc"]   = "يُفعَّل بعد 10 ثوانٍ — اذهب للشاشة الرئيسية",
            ["Sett_ViewLog"]         = "سجل الإشعارات",
            ["Sett_ViewLogDesc"]     = "اضغط لعرض السجل",
            ["Sett_SelectSound"]     = "اختر صوتاً",
            ["Sett_PlayWhich"]       = "أي صوت تريد تشغيله؟",
            ["Sett_TestWhich"]       = "أي صوت تريد للاختبار؟",
            ["Sett_TestAlarmTitle"]  = "تم ضبط المنبه التجريبي",
            ["Sett_TestAlarmBody"]   = "الصوت: {0}\nيُفعَّل بعد 10 ثوانٍ.\n\n1. اضغط موافق\n2. اذهب للشاشة الرئيسية\n3. انتظر الإشعار",
            ["Sett_LogTitle"]        = "سجل الإشعارات (تم النسخ!)",
            ["Sett_LogClearedTitle"] = "تم مسح السجل",
            ["Sett_LogClearedBody"]  = "تم مسح ملف السجل.",
            ["Cancel"]               = "إلغاء",
            ["OK"]                   = "موافق",

            // Calculation method names
            ["CalcMethod_0"]         = "Shia Ithna-Ansari",
            ["CalcMethod_1"]         = "University of Islamic Sciences, Karachi",
            ["CalcMethod_2"]         = "Islamic Society of North America (ISNA)",
            ["CalcMethod_3"]         = "Muslim World League (MWL)",
            ["CalcMethod_4"]         = "Umm Al-Qura University, Makkah",
            ["CalcMethod_5"]         = "Egyptian General Authority of Survey",
            ["CalcMethod_7"]         = "Institute of Geophysics, University of Tehran",
            ["CalcMethod_8"]         = "Gulf Region",
            ["CalcMethod_9"]         = "Kuwait",
            ["CalcMethod_10"]        = "Qatar",
            ["CalcMethod_11"]        = "Majlis Ugama Islam Singapura (MUIS)",
            ["CalcMethod_12"]        = "Union Organization Islamic de France",
            ["CalcMethod_13"]        = "Diyanet \u0130\u015fleri Ba\u015fkanl\u0131\u011f\u0131, Turkey",
            ["CalcMethod_14"]        = "Spiritual Administration of Muslims of Russia",
            ["CalcMethod_15"]        = "Moonsighting Committee Worldwide (Khalid Shaukat)",
            ["CalcMethod_16"]        = "Dubai",
            ["CalcMethod_17"]        = "Jabatan Kemajuan Islam Malaysia (JAKIM)",
            ["CalcMethod_18"]        = "Jordan",
            ["CalcMethod_19"]        = "Islamic University of Madinah",
            ["CalcMethod_20"]        = "Kementerian Agama Republik Indonesia",
            ["CalcMethod_21"]        = "Morocco",
            ["CalcMethod_22"]        = "Comunidade Islamica de Lisboa",
            ["CalcMethod_23"]        = "Ministry of Awqaf and Islamic Affairs, Algeria",
            ["CalcMethod_24"]        = "Caucasus Muslims Board (QMI)",
            ["CalcMethod_99"]        = "\u0645\u062e\u0635\u0635",

            // Calc config page
            ["CalcConfig_Title"]      = "\u0645\u0639\u0627\u0645\u0644\u0627\u062a \u0627\u0644\u062d\u0633\u0627\u0628",
            ["CalcConfig_Shafaq"]     = "\u0627\u0644\u0634\u0641\u0642",
            ["CalcConfig_ShafaqDesc"] = "\u0646\u0648\u0639 \u0627\u0644\u0634\u0641\u0642 \u0627\u0644\u0645\u0633\u062a\u062e\u062f\u0645 \u0644\u062d\u0633\u0627\u0628 \u0627\u0644\u0639\u0634\u0627\u0621",
            ["CalcConfig_Tune"]       = "\u0627\u0644\u0636\u0628\u0637 (\u0641\u0648\u0627\u0631\u0642 \u0627\u0644\u062f\u0642\u0627\u0626\u0642)",
            ["CalcConfig_TuneDesc"]   = "\u0641\u0648\u0627\u0631\u0642 \u0627\u0644\u062f\u0642\u0627\u0626\u0642 \u0644\u0643\u0644 \u0635\u0644\u0627\u0629 \u0645\u0641\u0635\u0648\u0644\u0629 \u0628\u0641\u0648\u0627\u0635\u0644",
            ["CalcConfig_School"]     = "\u0627\u0644\u0645\u0630\u0647\u0628 \u0627\u0644\u0641\u0642\u0647\u064a (\u0627\u0644\u0639\u0635\u0631)",
            ["CalcConfig_Midnight"]   = "\u0648\u0636\u0639 \u0645\u0646\u062a\u0635\u0641 \u0627\u0644\u0644\u064a\u0644",
            ["CalcConfig_LatAdj"]     = "\u062a\u0639\u062f\u064a\u0644 \u062e\u0637 \u0627\u0644\u0639\u0631\u0636",
            ["CalcConfig_Calendar"]   = "\u0637\u0631\u064a\u0642\u0629 \u0627\u0644\u062a\u0642\u0648\u064a\u0645",
            ["CalcConfig_Apply"]      = "\u062a\u0637\u0628\u064a\u0642",
            ["CalcConfig_Reset"]      = "\u0625\u0639\u0627\u062f\u0629 \u0627\u0644\u0636\u0628\u0637",
            ["Shafaq_General"]        = "\u0639\u0627\u0645",
            ["Shafaq_Ahmer"]          = "\u0623\u062d\u0645\u0631",
            ["Shafaq_Abyad"]          = "\u0623\u0628\u064a\u0636",
            ["School_Shafi"]          = "\u0634\u0627\u0641\u0639\u064a / \u0642\u064a\u0627\u0633\u064a",
            ["School_Hanafi"]         = "\u062d\u0646\u0641\u064a",
            ["Midnight_Standard"]     = "\u0642\u064a\u0627\u0633\u064a (\u0645\u0646\u062a\u0635\u0641 \u0627\u0644\u063a\u0631\u0648\u0628-\u0627\u0644\u0634\u0631\u0648\u0642)",
            ["Midnight_Jafari"]       = "\u062c\u0639\u0641\u0631\u064a (\u0645\u0646\u062a\u0635\u0641 \u0627\u0644\u063a\u0631\u0648\u0628-\u0627\u0644\u0641\u062c\u0631)",
            ["LatAdj_None"]           = "\u0628\u062f\u0648\u0646 \u062a\u0639\u062f\u064a\u0644",
            ["LatAdj_Middle"]         = "\u0645\u0646\u062a\u0635\u0641 \u0627\u0644\u0644\u064a\u0644",
            ["LatAdj_Seventh"]        = "\u0633\u0628\u0639 \u0627\u0644\u0644\u064a\u0644",
            ["LatAdj_Angle"]          = "\u0642\u0627\u0626\u0645 \u0639\u0644\u0649 \u0627\u0644\u0632\u0627\u0648\u064a\u0629",
            ["Calendar_HJCoSA"]       = "\u0647\u062c\u0631\u064a (HJCoSA)",
            ["Calendar_UAQ"]          = "\u0623\u0645 \u0627\u0644\u0642\u0631\u0649",
            ["Calendar_DIYANET"]      = "\u062f\u064a\u0627\u0646\u062a",
            ["Calendar_MATHEMATICAL"] = "\u0631\u064a\u0627\u0636\u064a",

            ["NoLocationTitle"]       = "لم يتم تحديد الموقع",
            ["NoLocationDesc"]        = "للمتابعة، امنح إذن الموقع — أو اختر مدينتك أدناه.",
            ["Or"]                    = "أو",
            ["OpenSettings"]          = "فتح الإعدادات",
            ["LocationPermission"]    = "إذن الموقع",
            ["LocationPermDenied"]    = "تم رفض الوصول إلى الموقع. يرجى تفعيله من إعدادات الجهاز.",
        },

        ["es"] = new()
        {
            ["Tab_Home"]              = "INICIO",
            ["Tab_Monthly"]           = "MENSUAL",
            ["Tab_Qibla"]             = "QIBLA",
            ["Tab_Quran"]             = "COR\u00c1N",
            ["Tab_Settings"]          = "AJUSTES",
            ["Greeting"]              = "Assalamu Alaikum",
            ["FastDay"]               = "D\u00eda de ayuno",
            ["UpcomingPrayer"]        = "PR\u00d3XIMA ORACI\u00d3N",
            ["Time"]                  = "HORA",
            ["StartsIn"]              = "COMIENZA EN",
            ["Hrs"]                   = "HORAS",
            ["Min"]                   = "MINUTOS",
            ["Sec"]                   = "SEGUNDOS",
            ["Local"]                 = "LOCAL",
            ["NextIn"]                = "LA ORACI\u00d3N TERMINA EN",
            ["DailyTimes"]            = "Horarios diarios",
            ["MonthlyTable"]          = "Tabla mensual",
            ["Prayer_Fajr"]           = "Fajr",
            ["Prayer_Sunrise"]        = "Amanecer",
            ["Prayer_Dhuhr"]          = "Dhuhr",
            ["Prayer_Asr"]            = "Asr",
            ["Prayer_Maghrib"]        = "Maghrib",
            ["Prayer_Isha"]           = "Isha",
            ["MonthlySchedule"]       = "Horarios mensuales de oraci\u00f3n",
            ["Date"]                  = "D\u00eda",
            ["BenefitOfMonth"]        = "BENEFICIO DEL MES",
            ["BenefitQuote"]          = "\u201cAprovecha cinco antes de cinco: tu juventud antes de tu vejez, tu salud antes de tu enfermedad...\u201d",
            ["BenefitAttribution"]    = "\u2014 Had\u00eds, Al-Hakim",
            ["Qibla"]                 = "Qibla",
            ["Quran"]                 = "Cor\u00e1n",
            ["ComingSoon"]            = "Pr\u00f3ximamente",
            ["Settings"]              = "Ajustes",
            ["AppLanguage"]           = "Idioma de la app",
            ["SelectLanguage"]        = "Selecciona tu idioma",
            ["Change"]                = "CAMBIAR",
            ["LocationThreshold"]     = "Umbral de actualizaci\u00f3n de ubicaci\u00f3n",
            ["LocationThresholdDesc"] = "Actualizar horarios al cambiar de ciudad tras recorrer esta distancia",
            ["NotificationsAndPrefs"] = "NOTIFICACIONES Y PREFERENCIAS",
            ["PrayerNotifications"]   = "Notificaciones de oraci\u00f3n",
            ["DarkMode"]              = "Modo oscuro",
            ["LocationServices"]      = "Servicios de ubicaci\u00f3n",
            ["CalculationMethod"]     = "M\u00c9TODO DE C\u00c1LCULO",
            ["FajrIshaMethod"]        = "M\u00e9todo de c\u00e1lculo",
            ["MuslimWorldLeague"]     = "Presidencia de Asuntos Religiosos (Turqu\u00eda)",
            ["Account"]               = "CUENTA",
            ["ProfileInformation"]    = "Informaci\u00f3n de perfil",
            ["UpdatePersonalDetails"] = "Actualiza tus datos personales",
            ["SelectCity"]            = "Seleccionar ciudad",
            ["SearchCityHint"]        = "Escribe un nombre de ciudad\u2026",
            ["UseCurrentLocation"]    = "Usar ubicaci\u00f3n actual",
            ["NoResults"]             = "No se encontraron resultados",
            ["CalcMethod"]            = "Método de cálculo",
            ["CalcMethodDiyanet"]     = "Diyanet",
            ["CalcMethodQMI"]         = "Junta de Musulmanes del Cáucaso",
            ["QiblaInstruction"]      = "Coloca tu dispositivo en una superficie plana y luego muévelo",
            ["Notif_Title"]           = "Hora de oraci\u00f3n",
            ["Notif_BeforeBody"]      = "{0} en {1} min",
            ["Notif_BeforeBody_H"]    = "{0} en {1}h {2}min",
            ["Notif_OnBody"]          = "La oraci\u00f3n {0} ha comenzado",
            ["Notif_EndsBody"]        = "{0} termina en {1} min",
            ["Notif_EndsBody_H"]      = "{0} termina en {1}h {2}min",
            ["AppliesToAll"]          = "Se aplica a todas las oraciones",
            ["CustomizePerPrayer"]    = "Personalizar por oraci\u00f3n",
            ["Sett_Before"]          = "Antes de la oraci\u00f3n",
            ["Sett_On"]              = "En la hora de oraci\u00f3n",
            ["Sett_Ends"]            = "La oraci\u00f3n termina en",
            ["Sett_SoundAdhan"]      = "Sonido",
            ["Sett_PlayNow"]         = "Reproducir ahora",
            ["Sett_PlayNowDesc"]     = "Reproduce el audio directamente \u2014 sin necesidad de notificaci\u00f3n",
            ["Sett_TestNotif"]       = "Notificaci\u00f3n de prueba",
            ["Sett_TestNotifDesc"]   = "Se activa en 10 s \u2014 ve a la pantalla de inicio",
            ["Sett_ViewLog"]         = "Registro de notificaciones",
            ["Sett_ViewLogDesc"]     = "Toca para ver el registro",
            ["Sett_SelectSound"]     = "Seleccionar sonido",
            ["Sett_PlayWhich"]       = "\u00bfQu\u00e9 sonido reproducir?",
            ["Sett_TestWhich"]       = "\u00bfQu\u00e9 sonido usar para la prueba?",
            ["Sett_TestAlarmTitle"]  = "Alarma de prueba programada",
            ["Sett_TestAlarmBody"]   = "Sonido: {0}\nSe activa en 10 segundos.\n\n1. Toca OK\n2. Ve a la pantalla de inicio\n3. Espera la notificaci\u00f3n",
            ["Sett_LogTitle"]        = "Registro de notificaciones (\u00a1Copiado!)",
            ["Sett_LogClearedTitle"] = "Registro eliminado",
            ["Sett_LogClearedBody"]  = "El archivo de registro ha sido eliminado.",
            ["Cancel"]               = "Cancelar",
            ["OK"]                   = "OK",

            // Calculation method names
            ["CalcMethod_0"]         = "Shia Ithna-Ansari",
            ["CalcMethod_1"]         = "University of Islamic Sciences, Karachi",
            ["CalcMethod_2"]         = "Islamic Society of North America (ISNA)",
            ["CalcMethod_3"]         = "Muslim World League (MWL)",
            ["CalcMethod_4"]         = "Umm Al-Qura University, Makkah",
            ["CalcMethod_5"]         = "Egyptian General Authority of Survey",
            ["CalcMethod_7"]         = "Institute of Geophysics, University of Tehran",
            ["CalcMethod_8"]         = "Gulf Region",
            ["CalcMethod_9"]         = "Kuwait",
            ["CalcMethod_10"]        = "Qatar",
            ["CalcMethod_11"]        = "Majlis Ugama Islam Singapura (MUIS)",
            ["CalcMethod_12"]        = "Union Organization Islamic de France",
            ["CalcMethod_13"]        = "Diyanet \u0130\u015fleri Ba\u015fkanl\u0131\u011f\u0131, Turkey",
            ["CalcMethod_14"]        = "Spiritual Administration of Muslims of Russia",
            ["CalcMethod_15"]        = "Moonsighting Committee Worldwide (Khalid Shaukat)",
            ["CalcMethod_16"]        = "Dubai",
            ["CalcMethod_17"]        = "Jabatan Kemajuan Islam Malaysia (JAKIM)",
            ["CalcMethod_18"]        = "Jordan",
            ["CalcMethod_19"]        = "Islamic University of Madinah",
            ["CalcMethod_20"]        = "Kementerian Agama Republik Indonesia",
            ["CalcMethod_21"]        = "Morocco",
            ["CalcMethod_22"]        = "Comunidade Islamica de Lisboa",
            ["CalcMethod_23"]        = "Ministry of Awqaf and Islamic Affairs, Algeria",
            ["CalcMethod_24"]        = "Caucasus Muslims Board (QMI)",
            ["CalcMethod_99"]        = "Personalizado",

            // Calc config page
            ["CalcConfig_Title"]      = "Par\u00e1metros de c\u00e1lculo",
            ["CalcConfig_Shafaq"]     = "Shafaq (Crep\u00fasculo)",
            ["CalcConfig_ShafaqDesc"] = "Tipo de crep\u00fasculo para el c\u00e1lculo de Isha",
            ["CalcConfig_Tune"]       = "Ajuste (offsets en minutos)",
            ["CalcConfig_TuneDesc"]   = "Offsets en minutos separados por comas para cada oraci\u00f3n",
            ["CalcConfig_School"]     = "Escuela jur\u00eddica (Asr)",
            ["CalcConfig_Midnight"]   = "Modo medianoche",
            ["CalcConfig_LatAdj"]     = "Ajuste de latitud",
            ["CalcConfig_Calendar"]   = "M\u00e9todo de calendario",
            ["CalcConfig_Apply"]      = "Aplicar",
            ["CalcConfig_Reset"]      = "Restablecer valores",
            ["Shafaq_General"]        = "General",
            ["Shafaq_Ahmer"]          = "Ahmer (Rojo)",
            ["Shafaq_Abyad"]          = "Abyad (Blanco)",
            ["School_Shafi"]          = "Shafi / Est\u00e1ndar",
            ["School_Hanafi"]         = "Hanafi",
            ["Midnight_Standard"]     = "Est\u00e1ndar (mitad puesta-salida del sol)",
            ["Midnight_Jafari"]       = "Jafari (mitad puesta del sol-Fajr)",
            ["LatAdj_None"]           = "Sin ajuste",
            ["LatAdj_Middle"]         = "Mitad de la noche",
            ["LatAdj_Seventh"]        = "Un s\u00e9ptimo de la noche",
            ["LatAdj_Angle"]          = "Basado en \u00e1ngulo",
            ["Calendar_HJCoSA"]       = "Hijri (HJCoSA)",
            ["Calendar_UAQ"]          = "Umm al-Qura (UAQ)",
            ["Calendar_DIYANET"]      = "Diyanet",
            ["Calendar_MATHEMATICAL"] = "Matem\u00e1tico",

            ["NoLocationTitle"]       = "Ubicaci\u00f3n no configurada",
            ["NoLocationDesc"]        = "Para continuar, otorga permiso de ubicaci\u00f3n \u2014 o selecciona tu ciudad abajo.",
            ["Or"]                    = "o",
            ["OpenSettings"]          = "Abrir ajustes",
            ["LocationPermission"]    = "Permiso de ubicaci\u00f3n",
            ["LocationPermDenied"]    = "El acceso a la ubicaci\u00f3n fue denegado. Por favor, act\u00edvalo en los ajustes de tu dispositivo.",
        },

        ["fr"] = new()
        {
            ["Tab_Home"]              = "ACCUEIL",
            ["Tab_Monthly"]           = "MENSUEL",
            ["Tab_Qibla"]             = "QIBLA",
            ["Tab_Quran"]             = "CORAN",
            ["Tab_Settings"]          = "PARAM\u00c8TRES",
            ["Greeting"]              = "Assalamu Alaikum",
            ["FastDay"]               = "Jour de je\u00fbne",
            ["UpcomingPrayer"]        = "PROCHAINE PRI\u00c8RE",
            ["Time"]                  = "HEURE",
            ["StartsIn"]              = "COMMENCE DANS",
            ["Hrs"]                   = "HEURES",
            ["Min"]                   = "MINUTES",
            ["Sec"]                   = "SECONDES",
            ["Local"]                 = "LOCAL",
            ["NextIn"]                = "LA PRI\u00c8RE SE TERMINE DANS",
            ["DailyTimes"]            = "Horaires du jour",
            ["MonthlyTable"]          = "Tableau mensuel",
            ["Prayer_Fajr"]           = "Fajr",
            ["Prayer_Sunrise"]        = "Lever du soleil",
            ["Prayer_Dhuhr"]          = "Dhuhr",
            ["Prayer_Asr"]            = "Asr",
            ["Prayer_Maghrib"]        = "Maghrib",
            ["Prayer_Isha"]           = "Isha",
            ["MonthlySchedule"]       = "Horaires mensuels de pri\u00e8re",
            ["Date"]                  = "Jour",
            ["BenefitOfMonth"]        = "B\u00c9N\u00c9FICE DU MOIS",
            ["BenefitQuote"]          = "\u201cProfite de cinq avant cinq\u00a0: ta jeunesse avant ta vieillesse, ta sant\u00e9 avant ta maladie...\u201d",
            ["BenefitAttribution"]    = "\u2014 Hadith, Al-Hakim",
            ["Qibla"]                 = "Qibla",
            ["Quran"]                 = "Coran",
            ["ComingSoon"]            = "Bient\u00f4t disponible",
            ["Settings"]              = "Param\u00e8tres",
            ["AppLanguage"]           = "Langue de l\u2019app",
            ["SelectLanguage"]        = "Choisissez votre langue",
            ["Change"]                = "CHANGER",
            ["LocationThreshold"]     = "Seuil de mise \u00e0 jour de localisation",
            ["LocationThresholdDesc"] = "Mettre \u00e0 jour les horaires si la ville change apr\u00e8s ce d\u00e9placement",
            ["NotificationsAndPrefs"] = "NOTIFICATIONS ET PR\u00c9F\u00c9RENCES",
            ["PrayerNotifications"]   = "Notifications de pri\u00e8re",
            ["DarkMode"]              = "Mode sombre",
            ["LocationServices"]      = "Services de localisation",
            ["CalculationMethod"]     = "M\u00c9THODE DE CALCUL",
            ["FajrIshaMethod"]        = "M\u00e9thode de calcul",
            ["MuslimWorldLeague"]     = "Pr\u00e9sidence des affaires religieuses (Turquie)",
            ["Account"]               = "COMPTE",
            ["ProfileInformation"]    = "Informations du profil",
            ["UpdatePersonalDetails"] = "Mettez \u00e0 jour vos informations personnelles",
            ["SelectCity"]            = "S\u00e9lectionner une ville",
            ["SearchCityHint"]        = "Tapez un nom de ville\u2026",
            ["UseCurrentLocation"]    = "Utiliser la localisation actuelle",
            ["NoResults"]             = "Aucun r\u00e9sultat trouv\u00e9",
            ["CalcMethod"]            = "Méthode de calcul",
            ["CalcMethodDiyanet"]     = "Diyanet",
            ["CalcMethodQMI"]         = "Direction des musulmans du Caucase",
            ["QiblaInstruction"]      = "Posez votre appareil sur une surface plate puis déplacez-le",
            ["Notif_Title"]           = "Heure de pri\u00e8re",
            ["Notif_BeforeBody"]      = "{0} dans {1} min",
            ["Notif_BeforeBody_H"]    = "{0} dans {1}h {2}min",
            ["Notif_OnBody"]          = "La pri\u00e8re {0} a commenc\u00e9",
            ["Notif_EndsBody"]        = "{0} se termine dans {1} min",
            ["Notif_EndsBody_H"]      = "{0} se termine dans {1}h {2}min",
            ["AppliesToAll"]          = "S\u2019applique \u00e0 toutes les pri\u00e8res",
            ["CustomizePerPrayer"]    = "Personnaliser par pri\u00e8re",
            ["Sett_Before"]          = "Avant la pri\u00e8re",
            ["Sett_On"]              = "\u00c0 l\u2019heure de la pri\u00e8re",
            ["Sett_Ends"]            = "La pri\u00e8re se termine dans",
            ["Sett_SoundAdhan"]      = "Son",
            ["Sett_PlayNow"]         = "Lire maintenant",
            ["Sett_PlayNowDesc"]     = "Lecture audio directe \u2014 pas besoin de notification",
            ["Sett_TestNotif"]       = "Notification de test",
            ["Sett_TestNotifDesc"]   = "Se d\u00e9clenche dans 10 s \u2014 allez \u00e0 l\u2019\u00e9cran d\u2019accueil",
            ["Sett_ViewLog"]         = "Journal des notifications",
            ["Sett_ViewLogDesc"]     = "Appuyez pour voir le journal",
            ["Sett_SelectSound"]     = "S\u00e9lectionner un son",
            ["Sett_PlayWhich"]       = "Quel son lire\u00a0?",
            ["Sett_TestWhich"]       = "Quel son utiliser pour le test\u00a0?",
            ["Sett_TestAlarmTitle"]  = "Alarme de test programm\u00e9e",
            ["Sett_TestAlarmBody"]   = "Son\u00a0: {0}\nSe d\u00e9clenche dans 10 secondes.\n\n1. Appuyez sur OK\n2. Allez \u00e0 l\u2019\u00e9cran d\u2019accueil\n3. Attendez la notification",
            ["Sett_LogTitle"]        = "Journal des notifications (Copi\u00e9\u00a0!)",
            ["Sett_LogClearedTitle"] = "Journal effac\u00e9",
            ["Sett_LogClearedBody"]  = "Le fichier journal a \u00e9t\u00e9 effac\u00e9.",
            ["Cancel"]               = "Annuler",
            ["OK"]                   = "OK",

            // Calculation method names
            ["CalcMethod_0"]         = "Shia Ithna-Ansari",
            ["CalcMethod_1"]         = "University of Islamic Sciences, Karachi",
            ["CalcMethod_2"]         = "Islamic Society of North America (ISNA)",
            ["CalcMethod_3"]         = "Muslim World League (MWL)",
            ["CalcMethod_4"]         = "Umm Al-Qura University, Makkah",
            ["CalcMethod_5"]         = "Egyptian General Authority of Survey",
            ["CalcMethod_7"]         = "Institute of Geophysics, University of Tehran",
            ["CalcMethod_8"]         = "Gulf Region",
            ["CalcMethod_9"]         = "Kuwait",
            ["CalcMethod_10"]        = "Qatar",
            ["CalcMethod_11"]        = "Majlis Ugama Islam Singapura (MUIS)",
            ["CalcMethod_12"]        = "Union Organization Islamic de France",
            ["CalcMethod_13"]        = "Diyanet \u0130\u015fleri Ba\u015fkanl\u0131\u011f\u0131, Turkey",
            ["CalcMethod_14"]        = "Spiritual Administration of Muslims of Russia",
            ["CalcMethod_15"]        = "Moonsighting Committee Worldwide (Khalid Shaukat)",
            ["CalcMethod_16"]        = "Dubai",
            ["CalcMethod_17"]        = "Jabatan Kemajuan Islam Malaysia (JAKIM)",
            ["CalcMethod_18"]        = "Jordan",
            ["CalcMethod_19"]        = "Islamic University of Madinah",
            ["CalcMethod_20"]        = "Kementerian Agama Republik Indonesia",
            ["CalcMethod_21"]        = "Morocco",
            ["CalcMethod_22"]        = "Comunidade Islamica de Lisboa",
            ["CalcMethod_23"]        = "Ministry of Awqaf and Islamic Affairs, Algeria",
            ["CalcMethod_24"]        = "Caucasus Muslims Board (QMI)",
            ["CalcMethod_99"]        = "Personnalis\u00e9",

            // Calc config page
            ["CalcConfig_Title"]      = "Param\u00e8tres de calcul",
            ["CalcConfig_Shafaq"]     = "Shafaq (Cr\u00e9puscule)",
            ["CalcConfig_ShafaqDesc"] = "Type de cr\u00e9puscule utilis\u00e9 pour le calcul de l\u2019Isha",
            ["CalcConfig_Tune"]       = "Ajustement (d\u00e9calages en minutes)",
            ["CalcConfig_TuneDesc"]   = "D\u00e9calages en minutes s\u00e9par\u00e9s par des virgules pour chaque pri\u00e8re",
            ["CalcConfig_School"]     = "\u00c9cole juridique (Asr)",
            ["CalcConfig_Midnight"]   = "Mode minuit",
            ["CalcConfig_LatAdj"]     = "Ajustement de latitude",
            ["CalcConfig_Calendar"]   = "M\u00e9thode de calendrier",
            ["CalcConfig_Apply"]      = "Appliquer",
            ["CalcConfig_Reset"]      = "R\u00e9initialiser",
            ["Shafaq_General"]        = "G\u00e9n\u00e9ral",
            ["Shafaq_Ahmer"]          = "Ahmer (Rouge)",
            ["Shafaq_Abyad"]          = "Abyad (Blanc)",
            ["School_Shafi"]          = "Shafi / Standard",
            ["School_Hanafi"]         = "Hanafi",
            ["Midnight_Standard"]     = "Standard (milieu coucher-lever du soleil)",
            ["Midnight_Jafari"]       = "Jafari (milieu coucher du soleil-Fajr)",
            ["LatAdj_None"]           = "Aucun ajustement",
            ["LatAdj_Middle"]         = "Milieu de la nuit",
            ["LatAdj_Seventh"]        = "Un septi\u00e8me de la nuit",
            ["LatAdj_Angle"]          = "Bas\u00e9 sur l\u2019angle",
            ["Calendar_HJCoSA"]       = "Hijri (HJCoSA)",
            ["Calendar_UAQ"]          = "Umm al-Qura (UAQ)",
            ["Calendar_DIYANET"]      = "Diyanet",
            ["Calendar_MATHEMATICAL"] = "Math\u00e9matique",

            ["NoLocationTitle"]       = "Aucune localisation d\u00e9finie",
            ["NoLocationDesc"]        = "Pour continuer, accordez la permission de localisation \u2014 ou s\u00e9lectionnez votre ville ci-dessous.",
            ["Or"]                    = "ou",
            ["OpenSettings"]          = "Ouvrir les param\u00e8tres",
            ["LocationPermission"]    = "Permission de localisation",
            ["LocationPermDenied"]    = "L\u2019acc\u00e8s \u00e0 la localisation a \u00e9t\u00e9 refus\u00e9. Veuillez l\u2019activer dans les param\u00e8tres de votre appareil.",
        },

        ["de"] = new()
        {
            ["Tab_Home"]              = "START",
            ["Tab_Monthly"]           = "MONATLICH",
            ["Tab_Qibla"]             = "QIBLA",
            ["Tab_Quran"]             = "QURAN",
            ["Tab_Settings"]          = "EINSTELLUNGEN",
            ["Greeting"]              = "Assalamu Alaikum",
            ["FastDay"]               = "Fastentag",
            ["UpcomingPrayer"]        = "N\u00c4CHSTES GEBET",
            ["Time"]                  = "ZEIT",
            ["StartsIn"]              = "BEGINNT IN",
            ["Hrs"]                   = "STUNDEN",
            ["Min"]                   = "MINUTEN",
            ["Sec"]                   = "SEKUNDEN",
            ["Local"]                 = "LOKAL",
            ["NextIn"]                = "GEBET ENDET IN",
            ["DailyTimes"]            = "Tageszeiten",
            ["MonthlyTable"]          = "Monatstabelle",
            ["Prayer_Fajr"]           = "Fajr",
            ["Prayer_Sunrise"]        = "Sonnenaufgang",
            ["Prayer_Dhuhr"]          = "Dhuhr",
            ["Prayer_Asr"]            = "Asr",
            ["Prayer_Maghrib"]        = "Maghrib",
            ["Prayer_Isha"]           = "Isha",
            ["MonthlySchedule"]       = "Monatliche Gebetszeiten",
            ["Date"]                  = "Tag",
            ["BenefitOfMonth"]        = "NUTZEN DES MONATS",
            ["BenefitQuote"]          = "\u201eNutze f\u00fcnf vor f\u00fcnf: deine Jugend vor deinem Alter, deine Gesundheit vor deiner Krankheit...\u201c",
            ["BenefitAttribution"]    = "\u2014 Hadith, Al-Hakim",
            ["Qibla"]                 = "Qibla",
            ["Quran"]                 = "Quran",
            ["ComingSoon"]            = "Demn\u00e4chst",
            ["Settings"]              = "Einstellungen",
            ["AppLanguage"]           = "App-Sprache",
            ["SelectLanguage"]        = "W\u00e4hle deine Sprache",
            ["Change"]                = "\u00c4NDERN",
            ["LocationThreshold"]     = "Standort-Aktualisierungsschwelle",
            ["LocationThresholdDesc"] = "Gebetszeiten neu laden, wenn sich die Stadt nach dieser Entfernung \u00e4ndert",
            ["NotificationsAndPrefs"] = "BENACHRICHTIGUNGEN & EINSTELLUNGEN",
            ["PrayerNotifications"]   = "Gebetsbenachrichtigungen",
            ["DarkMode"]              = "Dunkelmodus",
            ["LocationServices"]      = "Standortdienste",
            ["CalculationMethod"]     = "BERECHNUNGSMETHODE",
            ["FajrIshaMethod"]        = "Berechnungsmethode",
            ["MuslimWorldLeague"]     = "Pr\u00e4sidium f\u00fcr religi\u00f6se Angelegenheiten (T\u00fcrkei)",
            ["Account"]               = "KONTO",
            ["ProfileInformation"]    = "Profilinformationen",
            ["UpdatePersonalDetails"] = "Pers\u00f6nliche Daten aktualisieren",
            ["SelectCity"]            = "Stadt ausw\u00e4hlen",
            ["SearchCityHint"]        = "Stadtname eingeben\u2026",
            ["UseCurrentLocation"]    = "Aktuellen Standort verwenden",
            ["NoResults"]             = "Keine Ergebnisse gefunden",
            ["CalcMethod"]            = "Berechnungsmethode",
            ["CalcMethodDiyanet"]     = "Diyanet",
            ["CalcMethodQMI"]         = "Muslimische Verwaltung des Kaukasus",
            ["QiblaInstruction"]      = "Lege das Gerät auf eine flache Oberfläche und bewege es",
            ["Notif_Title"]           = "Gebetszeit",
            ["Notif_BeforeBody"]      = "{0} in {1} Min.",
            ["Notif_BeforeBody_H"]    = "{0} in {1}h {2}Min.",
            ["Notif_OnBody"]          = "Gebet {0} hat begonnen",
            ["Notif_EndsBody"]        = "{0} endet in {1} Min.",
            ["Notif_EndsBody_H"]      = "{0} endet in {1}h {2}Min.",
            ["AppliesToAll"]          = "Gilt f\u00fcr alle Gebetszeiten",
            ["CustomizePerPrayer"]    = "F\u00fcr jedes Gebet anpassen",
            ["Sett_Before"]          = "Vor der Gebetszeit",
            ["Sett_On"]              = "Zur Gebetszeit",
            ["Sett_Ends"]            = "Gebetszeit endet in",
            ["Sett_SoundAdhan"]      = "Ton",
            ["Sett_PlayNow"]         = "Jetzt abspielen",
            ["Sett_PlayNowDesc"]     = "Audio wird direkt abgespielt \u2014 keine Benachrichtigung erforderlich",
            ["Sett_TestNotif"]       = "Test-Benachrichtigung",
            ["Sett_TestNotifDesc"]   = "Wird in 10 Sek. ausgel\u00f6st \u2014 gehe zum Startbildschirm",
            ["Sett_ViewLog"]         = "Benachrichtigungsprotokoll",
            ["Sett_ViewLogDesc"]     = "Tippe zum Anzeigen des Protokolls",
            ["Sett_SelectSound"]     = "Ton ausw\u00e4hlen",
            ["Sett_PlayWhich"]       = "Welchen Ton abspielen?",
            ["Sett_TestWhich"]       = "Welchen Ton f\u00fcr den Test verwenden?",
            ["Sett_TestAlarmTitle"]  = "Test-Alarm eingestellt",
            ["Sett_TestAlarmBody"]   = "Ton: {0}\nWird in 10 Sekunden ausgel\u00f6st.\n\n1. OK tippen\n2. Zum Startbildschirm gehen\n3. Auf Benachrichtigung warten",
            ["Sett_LogTitle"]        = "Benachrichtigungsprotokoll (Kopiert!)",
            ["Sett_LogClearedTitle"] = "Protokoll gel\u00f6scht",
            ["Sett_LogClearedBody"]  = "Protokolldatei wurde gel\u00f6scht.",
            ["Cancel"]               = "Abbrechen",
            ["OK"]                   = "OK",

            // Calculation method names
            ["CalcMethod_0"]         = "Shia Ithna-Ansari",
            ["CalcMethod_1"]         = "University of Islamic Sciences, Karachi",
            ["CalcMethod_2"]         = "Islamic Society of North America (ISNA)",
            ["CalcMethod_3"]         = "Muslim World League (MWL)",
            ["CalcMethod_4"]         = "Umm Al-Qura University, Makkah",
            ["CalcMethod_5"]         = "Egyptian General Authority of Survey",
            ["CalcMethod_7"]         = "Institute of Geophysics, University of Tehran",
            ["CalcMethod_8"]         = "Gulf Region",
            ["CalcMethod_9"]         = "Kuwait",
            ["CalcMethod_10"]        = "Qatar",
            ["CalcMethod_11"]        = "Majlis Ugama Islam Singapura (MUIS)",
            ["CalcMethod_12"]        = "Union Organization Islamic de France",
            ["CalcMethod_13"]        = "Diyanet \u0130\u015fleri Ba\u015fkanl\u0131\u011f\u0131, Turkey",
            ["CalcMethod_14"]        = "Spiritual Administration of Muslims of Russia",
            ["CalcMethod_15"]        = "Moonsighting Committee Worldwide (Khalid Shaukat)",
            ["CalcMethod_16"]        = "Dubai",
            ["CalcMethod_17"]        = "Jabatan Kemajuan Islam Malaysia (JAKIM)",
            ["CalcMethod_18"]        = "Jordan",
            ["CalcMethod_19"]        = "Islamic University of Madinah",
            ["CalcMethod_20"]        = "Kementerian Agama Republik Indonesia",
            ["CalcMethod_21"]        = "Morocco",
            ["CalcMethod_22"]        = "Comunidade Islamica de Lisboa",
            ["CalcMethod_23"]        = "Ministry of Awqaf and Islamic Affairs, Algeria",
            ["CalcMethod_24"]        = "Caucasus Muslims Board (QMI)",
            ["CalcMethod_99"]        = "Benutzerdefiniert",

            // Calc config page
            ["CalcConfig_Title"]      = "Berechnungsparameter",
            ["CalcConfig_Shafaq"]     = "Shafaq (D\u00e4mmerung)",
            ["CalcConfig_ShafaqDesc"] = "Art der D\u00e4mmerung f\u00fcr die Isha-Berechnung",
            ["CalcConfig_Tune"]       = "Abstimmung (Minutenversatz)",
            ["CalcConfig_TuneDesc"]   = "Kommagetrennte Minutenvers\u00e4tze f\u00fcr jedes Gebet",
            ["CalcConfig_School"]     = "Juristische Schule (Asr)",
            ["CalcConfig_Midnight"]   = "Mitternachtsmodus",
            ["CalcConfig_LatAdj"]     = "Breitengradanpassung",
            ["CalcConfig_Calendar"]   = "Kalendermethode",
            ["CalcConfig_Apply"]      = "Anwenden",
            ["CalcConfig_Reset"]      = "Auf Standard zur\u00fccksetzen",
            ["Shafaq_General"]        = "Allgemein",
            ["Shafaq_Ahmer"]          = "Ahmer (Rot)",
            ["Shafaq_Abyad"]          = "Abyad (Wei\u00df)",
            ["School_Shafi"]          = "Shafi / Standard",
            ["School_Hanafi"]         = "Hanafi",
            ["Midnight_Standard"]     = "Standard (Mitte Sonnenuntergang-Aufgang)",
            ["Midnight_Jafari"]       = "Jafari (Mitte Sonnenuntergang-Fajr)",
            ["LatAdj_None"]           = "Keine Anpassung",
            ["LatAdj_Middle"]         = "Mitte der Nacht",
            ["LatAdj_Seventh"]        = "Ein Siebtel der Nacht",
            ["LatAdj_Angle"]          = "Winkelbasiert",
            ["Calendar_HJCoSA"]       = "Hijri (HJCoSA)",
            ["Calendar_UAQ"]          = "Umm al-Qura (UAQ)",
            ["Calendar_DIYANET"]      = "Diyanet",
            ["Calendar_MATHEMATICAL"] = "Mathematisch",

            ["NoLocationTitle"]       = "Kein Standort festgelegt",
            ["NoLocationDesc"]        = "Um fortzufahren, erlaube den Standortzugriff \u2014 oder w\u00e4hle unten deine Stadt.",
            ["Or"]                    = "oder",
            ["OpenSettings"]          = "Einstellungen \u00f6ffnen",
            ["LocationPermission"]    = "Standortberechtigung",
            ["LocationPermDenied"]    = "Standortzugriff wurde verweigert. Bitte aktiviere ihn in den Ger\u00e4teeinstellungen.",
        },
    };

    public static string CurrentLanguage => _currentLanguage;

    public static string CurrentLanguageDisplay => _currentLanguage switch
    {
        "tr" => "Türkçe",
        "az" => "Azərbaycan",
        "ru" => "Русский",
        "ar" => "العربية",
        "es" => "Español",
        "fr" => "Français",
        "de" => "Deutsch",
        _    => "English"
    };

    public static void LoadSavedLanguage()
    {
        _currentLanguage = Preferences.Get("AppLanguage", "en");
    }

    public static void SetLanguage(string languageCode)
    {
        _currentLanguage = languageCode;
        Preferences.Set("AppLanguage", languageCode);
    }

    public static string GetString(string key)
    {
        if (_translations.TryGetValue(_currentLanguage, out var dict) &&
            dict.TryGetValue(key, out var value))
            return value;

        // Fallback to English
        if (_translations["en"].TryGetValue(key, out var fallback))
            return fallback;

        return key;
    }
}
